### ISSUE TITLE
Trying to re-upload same file path not working

### ISSUE THREAD

**Issue by Samsy** [Jeremboo/dat.gui.image#1]
Not sure how much this is valuable for your project, 
been trying to re-upload another version of the same file but with same path to the uploader.
( working on photoshop, saving, uploading, working, saving, uploading etc.. is quite handy for designers ) 

Won't work that quick because the input 'change' event does not trigger as the path-file name is the same, but re-setting the input value to an empty string do work

After this line : 

https://github.com/Jeremboo/dat.gui.image/blob/master/src/index.js#L51

`this.__input.value = ""`

**Comment by Jeremboo** [comment]
Hey man, thanks for the feedback! 

Indeed, it's a good point. I fixed it according to your proposition and pushed the new version on npm. You should normally don't have the issue anymore! 

Thanks!
